<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test 1"
           tests="5"
           failures="3"
           errors="0"
           skipped="1"
           time="0,331">
    <properties></properties>

            <testcase
                name="teardown"
                time="0,001"
                classname="testcases.TestCase11_1">

            <failure type="java.lang.NullPointerException" message="Cannot invoke &quot;org.openqa.selenium.WebDriver.quit()&quot; because &quot;testcases.TestCase11_1.driver&quot; is null">
                <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "testcases.TestCase11_1.driver" is null
                testcases.TestCase11_1.teardown(TestCase11_1.java:187)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)org.testng.TestRunner.afterRun(TestRunner.java:958)org.testng.TestRunner.run(TestRunner.java:606)org.testng.SuiteRunner.runTest(SuiteRunner.java:380)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1226)org.testng.TestNG.runSuites(TestNG.java:1144)org.testng.TestNG.run(TestNG.java:1115)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </failure>
    </testcase>
            <testcase
                name="SimpleTest1"
                time="0,008"
                classname="testcases.TestCase11_1">

            <failure type="java.lang.NullPointerException" message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because &quot;this.extentTest&quot; is null">
                <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.extentTest" is null
                testcases.TestCase11_1.SimpleTest1(TestCase11_1.java:81)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:744)org.testng.TestRunner.run(TestRunner.java:602)org.testng.SuiteRunner.runTest(SuiteRunner.java:380)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1226)org.testng.TestNG.runSuites(TestNG.java:1144)org.testng.TestNG.run(TestNG.java:1115)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </failure>
    </testcase>
            <testcase
                name="SimpleTest2"
                time="0,005"
                classname="testcases.TestCase11_1">

            <failure type="java.lang.AssertionError" message="">
                <![CDATA[java.lang.AssertionError: 
                org.testng.AssertJUnit.fail(AssertJUnit.java:59)org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)testcases.TestCase11_1.SimpleTest2(TestCase11_1.java:92)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:744)org.testng.TestRunner.run(TestRunner.java:602)org.testng.SuiteRunner.runTest(SuiteRunner.java:380)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1226)org.testng.TestNG.runSuites(TestNG.java:1144)org.testng.TestNG.run(TestNG.java:1115)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </failure>
    </testcase>

            <testcase
                name="finishTest"
                time="0.0"
                classname="testcases.TestCase11_1">
            </testcase>

            <testcase
                name="loginWithCorrectUsernameAndPassword"
                time="0,317"
                classname="testcases.TestCase11_1">
            </testcase>
</testsuite>
