<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="2,287">
    <properties></properties>

            <testcase
                name="SimpleTest2"
                time="0,005"
                classname="testcases.TestCaseDia114">

            <failure type="java.lang.AssertionError" message="">
                <![CDATA[java.lang.AssertionError: 
                org.testng.AssertJUnit.fail(AssertJUnit.java:59)org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)testcases.TestCaseDia114.SimpleTest2(TestCaseDia114.java:55)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:744)org.testng.TestRunner.run(TestRunner.java:602)org.testng.SuiteRunner.runTest(SuiteRunner.java:380)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1226)org.testng.TestNG.runSuites(TestNG.java:1144)org.testng.TestNG.run(TestNG.java:1115)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </failure>
    </testcase>


            <testcase
                name="loginWithCorrectUsernameAndIncorrectPassword"
                time="0,826"
                classname="testcases.TestCaseDia114">
            </testcase>
            <testcase
                name="loginWithCorrectUsernameAndPassword"
                time="0,437"
                classname="testcases.TestCaseDia114">
            </testcase>
            <testcase
                name="loginWithNoUsernameAndPassword"
                time="0,393"
                classname="testcases.TestCaseDia114">
            </testcase>
            <testcase
                name="SimpleTest1"
                time="0,026"
                classname="testcases.TestCaseDia114">
            </testcase>
            <testcase
                name="loginWithIncorrectUsername"
                time="0,600"
                classname="testcases.TestCaseDia114">
            </testcase>
</testsuite>
